"""Build shared 16-pixel bitmap fonts. Dev-only dependency: Pillow.
Run from the repository root after PlatformIO has fetched GFX Library.
Use --sky-only to keep the existing pixel atlases unchanged.
"""

import json, re, sys, unicodedata
from pathlib import Path
from urllib.request import urlopen
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "bridge/designer"
SOURCES = {
    "silkscreen": ("silkscreen", "Silkscreen-Regular.ttf"),
    "pixelify": ("pixelifysans", "PixelifySans[wght].ttf"),
    "terminal": ("vt323", "VT323-Regular.ttf"),
    "modern": ("spacegrotesk", "SpaceGrotesk[wght].ttf"),
    "mono": ("jetbrainsmono", "JetBrainsMono[wght].ttf"),
}
fonts = {}
classic = (
    ROOT
    / "firmware/.pio/libdeps/quota_display/GFX Library for Arduino/src/font/glcdfont.h"
).read_text()
raw = [
    int(h, 16)
    for h in re.findall(
        r"0x([0-9a-fA-F]{2})", classic.split("= {", 1)[1].split("};", 1)[0]
    )
]
for name in ([] if "--sky-only" in sys.argv else ["pixel", *SOURCES]):
    if name != "pixel":
        folder, file = SOURCES[name]
        base = "https://raw.githubusercontent.com/google/fonts/main/ofl/" + folder + "/"
        path = OUT / "fonts" / file
        if not path.exists():
            from urllib.parse import quote

            path.write_bytes(urlopen(base + quote(file), timeout=20).read())
        license = OUT / "fonts" / (name + "-OFL.txt")
        if not license.exists():
            license.write_text(
                "\n".join(
                    line.rstrip()
                    for line in urlopen(base + "OFL.txt", timeout=20)
                    .read()
                    .decode()
                    .splitlines()
                )
                + "\n"
            )
        f = ImageFont.truetype(str(path), 16)
    glyphs = []
    for code in range(32, 256):
        char = chr(code)
        if name == "pixel":
            try:
                classic_code = ord(char.encode("cp437"))
            except (UnicodeEncodeError, TypeError):
                ascii_char = (
                    unicodedata.normalize("NFKD", char)
                    .encode("ascii", "ignore")
                    .decode()
                )
                classic_code = ord(ascii_char[:1] or "?")
            cols = raw[classic_code * 5 : classic_code * 5 + 5]
            width = 12
            rows = [
                sum((3 << (x * 2)) for x, c in enumerate(cols) if c & (1 << (y // 2)))
                for y in range(16)
            ]
        else:
            width = max(1, min(24, round(f.getlength(char)) + 1))
            im = Image.new("L", (24, 16))
            ImageDraw.Draw(im).text((0, -2), char, font=f, fill=255)
            rows = [
                sum(1 << x for x in range(width) if im.getpixel((x, y)) >= 100)
                for y in range(16)
            ]
        glyphs.append([width, *rows])
    fonts[name] = glyphs
if fonts:
    (OUT / "fonts.json").write_text(json.dumps(fonts, separators=(",", ":")))
    header = [
        "// Generated by bridge/generate_designer_fonts.py. Font notices: bridge/designer/fonts.",
        "#pragma once",
        "#include <stdint.h>",
        "struct DesignerGlyph { uint8_t width; uint32_t rows[16]; };",
        "static const DesignerGlyph designerFonts[6][224] = {",
    ]
    for glyphs in fonts.values():
        header.append(
            "{"
            + ",".join(
                "{" + str(g[0]) + ",{" + ",".join(str(v) for v in g[1:]) + "}}"
                for g in glyphs
            )
            + "},"
        )
    header.append("};")
    (ROOT / "firmware/include/DesignerFonts.h").write_text("\n".join(header) + "\n")
    print("Six identical font atlases generated for browser and device.")

# Flight typography uses native-size coverage masks instead of enlarged pixels.
# Keep the intentional pixel fonts unchanged. Both renderers consume these masks.
fonts = json.loads((OUT / "fonts.json").read_text())
smooth = {}
coverage = bytearray()
metrics = []
for name in ("modern", "mono"):
    smooth[name] = []
    for size in (16, 28, 42):
        font = ImageFont.truetype(str(OUT / "fonts" / SOURCES[name][1]), size)
        font.set_variation_by_axes([500 if size == 16 else 600])
        glyphs = []
        for code in range(32, 256):
            char = chr(code)
            advance = max(1, round(font.getlength(char)) + 1)
            mask = Image.new("L", (advance, size + 10))
            ImageDraw.Draw(mask).text((0, -2), char, font=font, fill=255)
            box = mask.getbbox() or (0, 0, 0, 0)
            x, y, right, bottom = box
            values = [round(v / 17) for v in mask.crop(box).tobytes()]
            packed = bytes((values[i] << 4) | (values[i + 1] if i + 1 < len(values) else 0) for i in range(0, len(values), 2))
            metrics.append([advance, x, y, right - x, bottom - y, len(coverage)])
            coverage.extend(packed)
            glyphs.append([advance, x, y, right - x, bottom - y, packed.hex()])
        smooth[name].append(glyphs)
fonts["smooth"] = smooth
(OUT / "fonts.json").write_text(json.dumps(fonts, separators=(",", ":")))
(ROOT / "firmware/include/DesignerSkyFonts.h").write_text(
    "// Generated by bridge/generate_designer_fonts.py. Existing font licenses apply.\n#pragma once\n"
    "struct SkyGlyph { uint8_t advance,x,y,w,h; uint32_t offset; };\n"
    "static const SkyGlyph skyGlyphs[1344] = {\n"
    + ",\n".join("{" + ",".join(map(str, g)) + "}" for g in metrics) + "\n};\n"
    + "static const uint8_t skyCoverage[] = {\n"
    + ",\n".join(",".join(map(str, coverage[i:i + 32])) for i in range(0, len(coverage), 32)) + "\n};\n"
)
print(f"Smooth flight fonts generated: {len(coverage)} bytes, 16 coverage levels.")
